another fix

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -32,7 +32,7 @@ jobs:
       run: dotnet build -c Release --no-restore
 
     - name: Run tests
-      run: if [[ $((dotnet test --logger "console;verbosity=detailed" | grep "Test Run Failed." | wc -c) -ne 0 ]]; then exit 1; else exit 0; fi
+      run: if [[ $((dotnet test --logger "console;verbosity=detailed" | grep "Test Run Failed.") | wc -c) -ne 0 ]]; then exit 1; else exit 0; fi
 
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v4
